version: "3"
services:
  backend:
    # use dockerfile
    build: '.'
    links:
      - redis:redis
    environment:
      REDIS_URL: redis://redis:36379
    ports:
      - "3000:3000"
  redis:
    image: redis
    container_name: cache
    ports:
      - 36379:6379
    restart: always
volumes:
  database-data:
